# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: xx
pipeline:
  - name: HFTransformersNLP
    model_weights: "rasa/LaBSE"
    model_name: "bert"
  - name: languagedetect.LanguageDetector
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
